import mongoose, { Model, Schema, model, models } from "mongoose";
import { ObjectId } from "mongoose";

export interface AutoPlaylistDocument {
  title: string;
  items: ObjectId[];
}

const autoGeneratedPlaylistSchema = new Schema<AutoPlaylistDocument>(
  {
    title: {
      type: String,
      required: true,
    },
    items: [
      {
        type: mongoose.Types.ObjectId,
        ref: "Audio",
        required: true,
      },
    ],
  },
  {
    timestamps: true,
  }
);

const AutoGeneratedPlaylist =
  models.AutoGeneratedPlaylist ||
  model("AutoGeneratedPlaylist", autoGeneratedPlaylistSchema);

export default AutoGeneratedPlaylist as Model<AutoPlaylistDocument>;
